### ISSUE TITLE
Cheat sheets need updating

### ISSUE THREAD

**Issue by florisvdh** [r-spatial/qgisprocess#155]
@ambarja can you have a look at https://r-spatial.github.io/qgisprocess/reference/index.html and decide what is to be updated in the cheat sheets? I could review updates in the google document if you like, or add some myself.

Overview of deprecated functions and replacements is at https://r-spatial.github.io/qgisprocess/reference/qgisprocess-deprecated.html.

**Comment by florisvdh** [comment]
@ambarja any chance that you could fix this soon? Otherwise I'll need to try taking over.

**Comment by ambarja** [comment]
Hi @florisvdh  👀  , it seems to me that you have access to editing within google slides, please let me know if you can access it.
Regards.

**Comment by florisvdh** [comment]
Yes indeed @ambarja, I can access them, thanks!
