### ISSUE TITLE
Include support for {terra} SpatVector

### ISSUE THREAD

**Issue by florisvdh** [r-spatial/qgisprocess#178]
Somehow we claimed to support {terra} for input/output, but what we essentially have is {terra} **`SpatRaster`** support. The QGIS types 'raster', 'layer' and 'multilayer' are currently all handled by `terra::rast()` and `terra::writeRaster()`, helped by `qgis_tmp_raster()`. This is to be extended to `SpatVector`, and may cause some refactoring.

**Comment by maxogden** [comment]
I just ran into this, 

```
library(terra)
library(qgisprocess)
#install.packages("remotes")
#remotes::install_github("JanCaha/r_package_qgis")

testlines <- vect('~/testlines.gpkg')

result <- qgis::qgis_pointsalonglines(
  INPUT = testlines,
  DISTANCE = 1e4
)
```

which throws 

```
Error in `as_qgis_argument()`:
! Don't know how to convert object of type 'SpatVector' to QGIS type 'source'
```

Would love to be able to use terra here!

**Comment by florisvdh** [comment]
Thanks for the interest @maxogden. For the time being, you can coerce `SpatVector` objects to {sf}, using `sf::st_as_sf(testlines)` in above case.
