### ISSUE TITLE
Is qgisprocess supports all algorithms which have an algorithm ID in QGIS

### ISSUE THREAD

**Issue by SpatLyu** [r-spatial/qgisprocess#181]
## I have a usage requirement ,I found in `QGIS`, it has an algorithm ID,as shown in the figure below:
![image](https://github.com/r-spatial/qgisprocess/assets/118346681/1d80ad7c-3fbe-459d-a61e-411466f35c2e)
## but I can't find it in `qgisprocess`:
```R
library(qgisprocess)
qgis_algorithms() |> 
  dplyr::filter(provider == 'qgis') |> 
  dplyr::filter(algorithm == 'qgis:eliminateselectedpolygons')
```
## the result is as follows:
![image](https://github.com/r-spatial/qgisprocess/assets/118346681/7214946c-990d-49f9-bf79-824e858f3b1d)

**Comment by florisvdh** [comment]
What does `qgis_search_algorithms("eliminateselectedpolygons")` return?

**Comment by SpatLyu** [comment]
an empty tibble:
![image](https://github.com/r-spatial/qgisprocess/assets/118346681/fdf2349f-4654-40fa-821b-6641ed19370b)

**Comment by SpatLyu** [comment]
I have also installed the QGIS 3.32.3, but I can't find this algorithm either. I don't know why `qgisprocess` can't fcompletely get my qgis desktop's algorithm

**Comment by SpatLyu** [comment]
for me , call `qgis_algorithms()` only returns `1075` algorithms from `8` providers:
![image](https://github.com/r-spatial/qgisprocess/assets/118346681/45762c54-8a26-4354-a944-a0fc52b743d8)
![image](https://github.com/r-spatial/qgisprocess/assets/118346681/3479e348-af9f-40b4-a2d2-bac402a38cdd)

**Comment by florisvdh** [comment]
Thanks. You're right, it's not currently supported. That is because the backend, `qgis_process` does not export this specific algorithm when listing algorithms. When run in the shell, and filtering for the 'eliminate' string (`qgis_process list | grep eliminate`), it will be found that this does indeed not return the `qgis:eliminateselectedpolygons` algorithm.

Nevertheless, we can get the documentation of the algorithm in R by running `cat(qgis_run(c("help", "qgis:eliminateselectedpolygons"))$stdout)`.

I can imagine this makes sense for the algorithm at hand: the `qgis_process` program was not designed for interacting with an active QGIS project with relation to selections, but as a standalone CLI program as in standalone R scripting with {qgisprocess}. However to make sure I will ask the QGIS devs to provide more clarity here.

**Comment by florisvdh** [comment]
> for me , call `qgis_algorithms()` only returns `1075` algorithms from `8` providers

Your output of `qgis_providers()` looks OK. If you need more algorithms, you must install the necessary providers in order to get them. Refer to https://docs.qgis.org/latest/en/docs/user_manual/processing/3rdParty.html and https://qgis.org/en/site/forusers/support.html for more information.

**Comment by SpatLyu** [comment]
Thanks for your timely reply! I have another problem with `qgisprocess`  indentifying the `QGIS` desktop's algorithm; I have enabled the `grassprovider` plugin :
![image](https://github.com/r-spatial/qgisprocess/assets/118346681/65f62b74-fd2c-4cb0-83a7-bf92d5048c4f)
but  when i call `qgis_providers()`,it can't find the `grassprovider` plugin, 
![image](https://github.com/r-spatial/qgisprocess/assets/118346681/39ac4815-296e-402e-8a0d-ab649b05d399)
therefore I can't use the algorithms provided by `grass`, 
but when I use `QGIS` 3.22.16 ，`grassprovider` is in `qgis_providers()`'s output ,what's trouble?

**Comment by florisvdh** [comment]
As above, see https://docs.qgis.org/latest/en/docs/user_manual/processing/3rdParty.html about installing GRASS GIS and make it work. In short, you need the grassprovider plugin enabled (it's builtin) and GRASS GIS must be installed in a way that the provider finds it. I'd guess you didn't yet have the GRASS GIS algorithms available in the QGIS GUI, which explains they do not come through among the algorithms. Maybe you didn't install GRASS GIS yet.

**Comment by SpatLyu** [comment]
Thanks, I have installed `QGIS 3.28.4 LTR` and  now I can use the algorithms from `grassprovider`!

**Comment by florisvdh** [comment]
Adding update about:

> I can imagine this makes sense for the algorithm at hand: the `qgis_process` program was not designed for interacting with an active QGIS project with relation to selections, but as a standalone CLI program as in standalone R scripting with {qgisprocess}. However to make sure I will ask the QGIS devs to provide more clarity here.

This has been confirmed (https://github.com/qgis/QGIS/issues/54914). Also, upcoming QGIS releases will give an error when requesting the documentation of such algorithms from {qgisprocess}, instead of returning that documentation.
