### ISSUE TITLE
Update _pkgdown.yaml & extra.css to restore navbar visuals with pkgdown 2.1.0

### ISSUE THREAD

**Issue by florisvdh** [r-spatial/qgisprocess#216]
For now I've frozen {pkgdown} at 2.0.9 since continuing current layout with pkgdown 2.1.0 (especially the navbar colours) seems not straightforward (at least to me).

The `extra.css` and probably `_pkgdown.yaml` files in the `pkgdown` directory will need updating.

With {pkgdown} 2.1.0 the navbar is black and the search field is gone:

![afbeelding](https://github.com/user-attachments/assets/b968e4c9-1ab7-472b-aae9-4f2108e2886a)

**Comment by SpatLyu** [comment]
How about the following rendering on my own PC using `pkgdown` 2.1.0
![image](https://github.com/user-attachments/assets/31c9ddaf-935a-45bc-9a81-2c7d2df25b93)

**Comment by SpatLyu** [comment]
I have submitted PR to fix this problem, please review,@florisvdh

The updated website rendered by my local PC looks like this:

![image](https://github.com/user-attachments/assets/5d5e3525-2b45-4799-a336-7f64ddc12e41)
